name: Build and release

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install
        run: npm ci -w packages/lib
      - name: Build
        run: npm run build -w packages/lib
      - name: Publish
        uses: menduz/oddish-action@3.1.0
        with:
          cwd: ./packages/lib
          access: public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
